"""
This folder contains the constants used during app implementation.
"""

FREE_DELI_CART_VALUE = 20000

MIN_FREECHARGE_CART_VALUE = 1000

DELI_BASE_DISTANCE = 1000
DELI_BASE_FEE = 200
DELI_DISTANCE_INTERVAL = 500
DELI_FEE_PER_INTERVAL = 100

MAX_FREECHARGE_NUM_ITEMS = 4
FEE_PER_EXCESS_ITEM = 50
MAX_NO_BULKFEE_NUM_ITEMS = 12
BULK_FEE = 120

FRI_RUSH_RATE = 1.2
FRIDAY_IDX = 5  # System constant
RUSH_HOUR_START = 15
RUSH_HOUR_END = 19

MAX_DELI_FEE = 1500